import React from 'react';

interface TermsOfServiceProps {
  onHome: () => void;
}

export const TermsOfServicePage: React.FC<TermsOfServiceProps> = ({ onHome }) => {
  return (
    <div className="min-h-screen bg-bg relative pt-24 md:pt-32 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 relative z-10">
        <button 
          onClick={onHome}
          className="mb-8 flex items-center gap-2 text-sm text-txt3 hover:text-txt transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6"/></svg>
          Back to Home
        </button>

        <div className="bg-[var(--theme-form-bg)] backdrop-blur-md border border-border2 rounded-2xl shadow-[0_0_50px_var(--theme-shadow-heavy)] p-8 md:p-12 mb-12 markdown-body text-txt2 text-[15px] leading-relaxed">
          <div className="text-center mb-12 border-b border-border2 pb-8">
            <h1 className="text-3xl md:text-5xl font-heading font-bold text-txt mb-4 tracking-tight">Terms of Service</h1>
            <p className="text-txt3">Last Updated: April 20, 2026 | Effective Date: April 20, 2026</p>
          </div>

          <div className="space-y-8">
            <div className="font-bold text-txt bg-bg p-5 rounded-xl border border-border2">
              <p className="mb-0 text-sm leading-relaxed tracking-wider uppercase">
                PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE ACCESSING OR USING THE PHARMAHEAD PLATFORM. BY CREATING AN ACCOUNT, ACCESSING, OR USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT USE THE PLATFORM.
              </p>
            </div>

            <p>
              These Terms of Service ("Terms") constitute a legally binding agreement between you ("User", "you", or "your") and Leevon Labs Private Limited ("Leevon Labs", "we", "us", or "our"), a company incorporated under the Companies Act, 2013, with its registered office at 6-44, Allavaram Main Road, Near Gantalamma Temple, Allavaram, East Godavari, Andhra Pradesh, India – 533217, governing your access to and use of PharmaHead — our B2B pharma trade operating platform ("Platform" or "Services") available at <strong>pharmahead.app</strong> and its associated applications.
            </p>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">Definitions</h2>
              <p className="mb-3">The following capitalised terms shall have the meanings set out below:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>"Platform"</strong> means the PharmaHead web application, desktop application (Electron), Android mobile application, backend API, and all associated interfaces and services</li>
                <li><strong>"Services"</strong> means all features, modules, and functionalities provided through the Platform, including but not limited to order management, inventory management, billing, GST compliance, collections, sales force management, and AI-assisted invoice parsing</li>
                <li><strong>"User"</strong> means any individual or entity that creates an account on or accesses the Platform, including Main Wholesalers, Wholesalers, Retailers, Salesmen, and Administrators</li>
                <li><strong>"User Content"</strong> means any data, information, text, documents, images, or other content uploaded, inputted, or generated by the User through the Platform</li>
                <li><strong>"Subscription"</strong> means a paid plan (Billing, Basic, Pro, or Superior) that grants the User access to designated features of the Platform</li>
                <li><strong>"Confidential Information"</strong> means all non-public information relating to the business, operations, customers, finances, technology, or strategies of either party that is disclosed in connection with these Terms</li>
                <li><strong>"Applicable Laws"</strong> means all laws, regulations, rules, orders, and judicial decisions of India applicable to the subject matter hereof, including but not limited to the Information Technology Act 2000, DPDP Act 2023, GST laws, Drugs and Cosmetics Act 1940, and the Companies Act 2013</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">Eligibility</h2>
              <p className="mb-3">By using the Platform, you represent and warrant that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You are at least 18 years of age</li>
                <li>You have the legal capacity and authority to enter into a binding agreement</li>
                <li>If registering on behalf of a company, partnership, or other legal entity, you have the authority to bind that entity to these Terms</li>
                <li>You are not located in a jurisdiction where the use of the Platform is prohibited under Applicable Laws</li>
                <li>All registration information you provide is accurate, current, and complete</li>
                <li>Your use of the Platform complies with all Applicable Laws, including laws governing the sale, distribution, and record-keeping of pharmaceutical products in India</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">Account Registration and Security</h2>
              <p className="mb-3">To access the Platform, you must create an account by providing accurate information including your name, business name, GSTIN, Drug License details, contact information, and other details required for your role.</p>
              <p className="mb-3">You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>Maintaining the confidentiality of your account credentials (username and password)</li>
                <li>All activities that occur under your account, whether or not authorised by you</li>
                <li>Immediately notifying us at support@pharmahead.app if you suspect unauthorised access to your account</li>
                <li>Ensuring that all users accessing the Platform under your account comply with these Terms</li>
              </ul>
              <p className="mb-3">Leevon Labs reserves the right to suspend or terminate accounts that contain inaccurate information, are used in violation of these Terms, or are compromised by unauthorised use. We are not liable for any loss or damage arising from your failure to maintain account security.</p>
              <p>Account approval for Wholesalers and Main Wholesalers is subject to verification and approval by Leevon Labs. We reserve the right to approve, reject, or revoke account access at our sole discretion.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">4. Subscription Plans and Fees</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">4.1 Plans and Pricing</h3>
              <p className="mb-3">Access to certain features of the Platform requires a paid Subscription. The following plans are currently available:</p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li><strong>Billing Plan:</strong> ₹499/month or ₹4,999/year — provides access to quick sale billing, basic invoice generation, and GST dashboard</li>
                <li><strong>Basic Plan:</strong> ₹999/month — provides access to full order management, retailer management, inventory tracking, and ledger and collections</li>
                <li><strong>Pro Plan:</strong> ₹1,999/month or ₹19,999/year — includes all Basic features plus sales team management, AI invoice import, WhatsApp and SMS reminders, and analytics</li>
                <li><strong>Superior Plan:</strong> ₹2,499/month or ₹24,999/year — includes all Pro features plus GSTR-2B reconciliation, e-invoice generation, Tally export, and priority support</li>
              </ul>
              <p className="mb-6">Pricing is exclusive of applicable taxes (including GST). All fees are quoted in Indian Rupees (INR). The Desktop (Electron) application is licensed separately and is not included in any of the above plans.</p>

              <h3 className="text-lg font-bold text-txt mt-6 mb-3">4.2 Billing and Payment</h3>
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>Subscription fees are payable in advance (monthly or annually, as selected)</li>
                <li>Payment must be made through the payment methods accepted on the Platform</li>
                <li>Fees are non-refundable except as expressly stated in our Cancellation and Refund Policy</li>
                <li>Failure to pay subscription fees will result in suspension of access to paid features</li>
                <li>We reserve the right to modify pricing upon 30 days' prior written notice</li>
              </ul>

              <h3 className="text-lg font-bold text-txt mt-6 mb-3">4.3 Free Trial and Promotions</h3>
              <p className="mb-6">Leevon Labs may, at its discretion, offer free trial periods or promotional pricing. Free trial terms will be communicated at the time of offer. Upon expiry of a free trial, continued use requires a paid Subscription.</p>

              <h3 className="text-lg font-bold text-txt mt-6 mb-3">4.4 Coupon Codes</h3>
              <p>Coupon codes may be applied at the time of subscription purchase. Coupons are subject to individual terms and cannot be combined unless explicitly stated. Leevon Labs reserves the right to withdraw or modify coupon terms at any time.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">5. Acceptable Use Policy</h2>
              <p className="mb-3">By using the Platform, you agree that you will NOT:</p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>Use the Platform for any unlawful purpose or in violation of any Applicable Laws, including laws governing pharmaceutical distribution and GST compliance in India</li>
                <li>Upload, transmit, or distribute any User Content that is false, misleading, fraudulent, defamatory, obscene, or infringing of third-party rights</li>
                <li>Attempt to gain unauthorised access to any part of the Platform, its servers, or any connected systems</li>
                <li>Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the Platform</li>
                <li>Use automated scripts, bots, scrapers, or crawlers to extract data from the Platform without our prior written consent</li>
                <li>Interfere with, disrupt, or impose an unreasonable load on the Platform's infrastructure</li>
                <li>Misrepresent your identity, business credentials, GSTIN, Drug License, or other regulatory information</li>
                <li>Use the Platform to send unsolicited commercial communications to third parties</li>
                <li>Introduce malware, viruses, or other harmful code into the Platform</li>
                <li>Circvent, remove, or disable any security, access control, or licensing features of the Platform</li>
                <li>Share your account credentials with unauthorised third parties</li>
                <li>Use the Platform for competitive intelligence gathering without our consent</li>
              </ul>
              <p>Any violation of this Acceptable Use Policy may result in immediate suspension or termination of your account without notice or refund.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">6. User Content and Data</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">6.1 Ownership of User Content</h3>
              <p className="mb-6">You retain full ownership of all User Content that you upload or input into the Platform. Leevon Labs does not claim any intellectual property rights over your User Content.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">6.2 License to Leevon Labs</h3>
              <p className="mb-6">By uploading User Content to the Platform, you grant Leevon Labs a limited, non-exclusive, royalty-free licence to use, store, process, and display such User Content solely for the purpose of providing the Services to you. This licence terminates upon deletion of your account, subject to any legal retention obligations.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">6.3 Your Responsibilities</h3>
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>You are solely responsible for the accuracy, legality, and completeness of all User Content</li>
                <li>You warrant that you have all necessary rights and permissions to upload the User Content and to grant the licence described above</li>
                <li>You are responsible for ensuring that medicines, batches, and inventory data entered into the Platform accurately reflect your actual stock</li>
                <li>You are responsible for reviewing and verifying AI-parsed invoice data before confirming any stock import</li>
                <li>You are solely responsible for the accuracy of GST returns generated using Platform data</li>
              </ul>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">6.4 AI-Assisted Features</h3>
              <p className="mb-3">The Platform uses AI services (including Google Gemini and Anthropic Claude) to assist with invoice parsing and stock import. You acknowledge that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI parsing results are suggestions and must be reviewed and confirmed by you before use</li>
                <li>Leevon Labs makes no warranty as to the accuracy or completeness of AI-parsed data</li>
                <li>You bear full responsibility for any stock import decisions made based on AI-parsed data</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">7. Intellectual Property</h2>
              <p className="mb-3">All intellectual property rights in and to the Platform, including but not limited to software code, algorithms, designs, user interface, logos, trademarks, and documentation, are and shall remain the exclusive property of Leevon Labs or its licensors. "PharmaHead" and the PH logo are trademarks of Leevon Labs Private Limited.</p>
              <p className="mb-3">Nothing in these Terms grants you any right, title, or interest in the Platform's intellectual property except the limited right to use the Platform in accordance with your Subscription and these Terms.</p>
              <p>You shall not use Leevon Labs' trademarks, trade names, or logos without our prior written consent.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">8. Transactions Between Users</h2>
              <p className="mb-3">The Platform facilitates B2B transactions between Wholesalers and Retailers. Leevon Labs is a technology service provider and is NOT a party to any transaction between Users. Specifically:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Leevon Labs does not take title to, possession of, or responsibility for any pharmaceutical products transacted through the Platform</li>
                <li>Leevon Labs does not verify the quality, safety, regulatory compliance, or fitness for purpose of any products listed or ordered through the Platform</li>
                <li>All commercial terms, pricing, delivery conditions, return policies, and payment arrangements between Wholesalers and Retailers are determined exclusively by those parties</li>
                <li>Leevon Labs does not guarantee payment by any Retailer to any Wholesaler, or delivery by any Wholesaler to any Retailer</li>
                <li>Any disputes between Users must be resolved directly between the relevant parties — Leevon Labs is not an arbitrator or mediator of inter-User disputes</li>
                <li>Users are solely responsible for obtaining all regulatory licences, drug licenses, GST registrations, and other approvals required for their pharmaceutical business operations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">9. GST and Compliance Responsibility</h2>
              <p className="mb-3">PharmaHead provides tools to assist with GST compliance, including GSTR-1 exports, GSTR-2B reconciliation, and e-invoice generation. However:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You are solely responsible for reviewing, verifying, and filing your GST returns using data generated by the Platform</li>
                <li>Leevon Labs does not guarantee that GST reports generated by the Platform will be accepted by the GST portal or GSTN</li>
                <li>You must ensure that all invoice data, HSN codes, tax rates, and GST registration details entered into the Platform are accurate</li>
                <li>Leevon Labs shall not be liable for any tax penalties, interest, or regulatory consequences arising from inaccurate data entered by you or from GST filing decisions made by you</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">10. E-Invoice (IRN) Generation</h2>
              <p className="mb-3">For eligible Users, the Platform integrates with a government-approved e-invoice service provider to generate Invoice Reference Numbers (IRN). You acknowledge that:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Successful IRN generation depends on accurate invoice data and the availability of the e-invoice provider's API</li>
                <li>Leevon Labs shall use reasonable endeavours to ensure IRN generation but does not guarantee uptime of the e-invoice API</li>
                <li>You are responsible for verifying IRN records and for compliance with e-invoicing mandates under GST law</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">11. Disclaimers and Limitation of Liability</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">11.1 Disclaimer of Warranties</h3>
              <p className="mb-4 font-semibold text-txt uppercase text-sm leading-relaxed p-4 bg-bg rounded-lg border border-border2">
                THE PLATFORM AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR UNINTERRUPTED OR ERROR-FREE OPERATION.
              </p>
              <p className="mb-3">Leevon Labs does not warrant that:</p>
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>The Platform will be free from errors, bugs, or security vulnerabilities at all times</li>
                <li>Data loss will never occur — you are strongly advised to maintain independent backups of critical business data</li>
                <li>AI-assisted features will produce accurate results in all cases</li>
              </ul>

              <h3 className="text-lg font-bold text-txt mt-6 mb-3">11.2 Limitation of Liability</h3>
              <p className="mb-3 font-semibold text-txt uppercase text-sm">
                TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LEEVON LABS SHALL NOT BE LIABLE FOR:
              </p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>Any indirect, incidental, special, consequential, or punitive damages</li>
                <li>Loss of profits, revenue, business, data, goodwill, or anticipated savings</li>
                <li>Any losses arising from your reliance on AI-parsed data that has not been independently verified</li>
                <li>Any tax penalties, interest, or regulatory consequences arising from GST filing decisions</li>
                <li>Any losses arising from transactions between Users conducted through the Platform</li>
                <li>Any losses due to Force Majeure events (see Section 14)</li>
              </ul>
              <p className="font-semibold text-txt uppercase text-sm p-4 bg-bg rounded-lg border border-border2">
                IN ANY EVENT, LEEVON LABS' TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE TOTAL SUBSCRIPTION FEES ACTUALLY PAID BY YOU TO LEEVON LABS IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">12. Indemnification</h2>
              <p className="mb-3">You shall indemnify, defend, and hold harmless Leevon Labs, its directors, officers, employees, agents, and affiliates from and against any and all claims, losses, damages, liabilities, costs, and expenses (including reasonable legal fees) arising from or relating to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Your use of the Platform in violation of these Terms or Applicable Laws</li>
                <li>Your User Content, including any claim that it infringes third-party rights</li>
                <li>Any transaction between you and another User conducted through the Platform</li>
                <li>Your pharmaceutical business operations, including any regulatory non-compliance</li>
                <li>Your failure to maintain the security of your account credentials</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">13. Confidentiality</h2>
              <p className="mb-3">Each party agrees to maintain the confidentiality of the other party's Confidential Information and to use it solely for the purpose of performing obligations under these Terms. Neither party shall disclose Confidential Information to any third party without the prior written consent of the disclosing party, except as required by Applicable Laws or legal process.</p>
              <p className="mb-3">For the purpose of these Terms, the Platform's software architecture, algorithms, pricing strategies, and unreleased features constitute the Confidential Information of Leevon Labs. User business data, customer lists, and financial information constitute the User's Confidential Information.</p>
              <p>Confidentiality obligations survive termination of these Terms for a period of 5 (five) years.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">14. Force Majeure</h2>
              <p className="mb-3">Leevon Labs shall not be liable for any delay or failure to perform its obligations under these Terms caused by events beyond its reasonable control, including but not limited to acts of God, natural disasters, pandemic, government actions, power outages, internet disruptions, failure of third-party APIs (including GST portal, e-invoice providers, or payment gateways), or cyber-attacks ("Force Majeure Events").</p>
              <p>In the event of a Force Majeure Event, Leevon Labs will promptly notify affected Users and use reasonable efforts to restore Services as soon as practicable.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">15. Term and Termination</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">15.1 Term</h3>
              <p className="mb-6">These Terms commence when you first access the Platform and continue until terminated by either party.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">15.2 Termination by You</h3>
              <p className="mb-6">You may terminate your Subscription at any time by providing notice through the Platform settings. Termination takes effect at the end of the current billing period. No refunds are provided for the unused portion of any billing period, except as provided in our Cancellation and Refund Policy.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">15.3 Termination by Leevon Labs</h3>
              <p className="mb-3">We may suspend or terminate your account at any time, with or without notice, if:</p>
              <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>You breach any provision of these Terms</li>
                <li>You engage in fraudulent, illegal, or harmful conduct</li>
                <li>Your account is used in a manner that endangers the Platform or other Users</li>
                <li>You fail to pay subscription fees</li>
                <li>We discontinue the Platform or specific services</li>
              </ul>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">15.4 Effect of Termination</h3>
              <p className="mb-3">Upon termination:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Your access to the Platform will be revoked</li>
                <li>You must immediately cease all use of the Platform</li>
                <li>Leevon Labs will retain your data in accordance with its data retention policy (Section 7 of the Privacy Policy) and applicable law</li>
                <li>Provisions of these Terms that by their nature should survive termination (including IP rights, indemnification, disclaimers, and governing law) shall survive</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">16. Modifications to the Platform and Terms</h2>
              <p className="mb-3">Leevon Labs reserves the right to:</p>
              <ul className="list-disc pl-6 space-y-2 mb-4">
                <li>Add, modify, or remove features or services from the Platform at any time, including changes to plan features</li>
                <li>Modify these Terms at any time by posting the updated Terms on the Platform and notifying Users</li>
              </ul>
              <p>Material changes to these Terms will be notified via the Platform dashboard and/or email at least 15 days in advance. Your continued use of the Platform after the effective date of the updated Terms constitutes your acceptance. If you do not accept the changes, you must stop using the Platform before the effective date.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">17. Governing Law and Dispute Resolution</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">17.1 Governing Law</h3>
              <p className="mb-6">These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">17.2 Dispute Resolution</h3>
              <p className="mb-3">In the event of any dispute, claim, or controversy arising out of or relating to these Terms or the Services ("Dispute"), the parties shall first attempt to resolve the Dispute amicably through good faith negotiation within 30 days of written notice of the Dispute.</p>
              <p className="mb-3">If the Dispute cannot be resolved through negotiation, it shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, as amended. The arbitration shall be conducted by a sole arbitrator mutually appointed by the parties. The seat of arbitration shall be Bangalore, Karnataka, India. The language of arbitration shall be English. The arbitral award shall be final and binding.</p>
              <p className="mb-6">Nothing in this clause shall prevent either party from seeking urgent injunctive or other equitable relief from a court of competent jurisdiction.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">17.3 Jurisdiction</h3>
              <p>Subject to the arbitration clause above, the courts at Bangalore, Karnataka, India shall have exclusive jurisdiction over any matter arising from or relating to these Terms.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">18. General Provisions</h2>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.1 Entire Agreement</h3>
              <p className="mb-6">These Terms, together with the Privacy Policy and any additional terms applicable to specific services, constitute the entire agreement between the parties regarding the subject matter hereof and supersede all prior agreements, understandings, and communications.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.2 Severability</h3>
              <p className="mb-6">If any provision of these Terms is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it enforceable.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.3 Waiver</h3>
              <p className="mb-6">The failure of Leevon Labs to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision. Any waiver must be in writing and signed by an authorised representative of Leevon Labs.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.4 Assignment</h3>
              <p className="mb-6">You may not assign or transfer any rights or obligations under these Terms without our prior written consent. Leevon Labs may freely assign these Terms in connection with a merger, acquisition, or sale of all or substantially all of its assets.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.5 No Partnership or Agency</h3>
              <p className="mb-6">Nothing in these Terms shall create or be deemed to create a partnership, joint venture, employment, or agency relationship between the parties. You are an independent business using the Platform as a tool.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.6 Notices</h3>
              <p className="mb-6">Notices under these Terms shall be sent to: (i) you, at your registered email address; and (ii) Leevon Labs, at legal@pharmahead.app or at its registered office address. Notices shall be deemed received upon confirmed delivery or 48 hours after sending, whichever is earlier.</p>
              
              <h3 className="text-lg font-bold text-txt mt-6 mb-3">18.7 Language</h3>
              <p>These Terms are written in English. If translated into any other language, the English version shall prevail in the event of any inconsistency.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-txt mb-4 mt-10">19. Contact Information</h2>
              <p className="mb-4">For any questions, concerns, or notices regarding these Terms of Service:</p>
              <div className="bg-bg p-6 rounded-xl border border-border2 space-y-2">
                <p><strong>Company:</strong> Leevon Labs Private Limited</p>
                <p><strong>Product:</strong> PharmaHead (pharmahead.app)</p>
                <p><strong>Email:</strong> <a href="mailto:admin@pharmahead.app" className="text-ph-lt hover:underline">admin@pharmahead.app</a></p>
                <p><strong>Support:</strong> <a href="mailto:support@pharmahead.app" className="text-ph-lt hover:underline">support@pharmahead.app</a></p>
                <p><strong>Phone:</strong> 7780763121</p>
                <p className="pt-2 border-t border-border2 mt-4 inline-block w-full"><strong>Address:</strong><br/>6-44, Allavaram Main Road, East Godavari, Andhra Pradesh – 533217</p>
              </div>
            </section>

            <div className="text-center pt-8 border-t border-border2 mt-12 text-sm text-txt3">
              <p>— End of Legal Documents —</p>
              <p className="mt-2">© 2026 Leevon Labs Private Limited. All rights reserved.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
